### ISSUE TITLE
pip install failed with "No such file or directory: 'README.md'"

### ISSUE THREAD

**Issue by askulkarni2** [lazywei/psync#1]
My pip install failed with the following error message. 

```
$python --version                                                                           
Python 2.7.11

$ pip --version       
pip 9.0.1 from /home/akulkarni/.pyenv/versions/2.7.11/lib/python2.7/site-packages (python 2.7)


$ pip install project-sync                                                                   
Collecting project-sync
  Downloading project-sync-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/akulkarni/pip-build-oGOmIx/project-sync/setup.py", line 6, in <module>
        with open('README.md') as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by corradomatt** [comment]
I'm getting the same result

**Comment by lazywei** [comment]
Hi @askulkarni2 @corradomatt 

Thanks for reporting.

I just added Python 2 support at the version `0.2.0`. Could you please try again (after deleting any possible cache left by previous pip installation) and see if the issue is fixed?

Here is what I got on my laptop:
```
$ pip --version
pip 9.0.1 from /Users/lazywei/.pyenv/versions/2.7.11/lib/python2.7/site-packages (python 2.7)

$ pip install project-sync
Collecting project-sync
  Using cached project_sync-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: PyYAML>=3.12 in /Users/lazywei/.pyenv/versions/2.7.11/lib/python2.7/site-packages (from project-sync)
Requirement already satisfied: Click>=6.0 in /Users/lazywei/.pyenv/versions/2.7.11/lib/python2.7/site-packages (from project-sync)
Requirement already satisfied: watchdog>=0.8.3 in /Users/lazywei/.pyenv/versions/2.7.11/lib/python2.7/site-packages (from project-sync)
Requirement already satisfied: argh>=0.24.1 in /Users/lazywei/.pyenv/versions/2.7.11/lib/python2.7/site-packages (from watchdog>=0.8.3->project-sync)
Requirement already satisfied: pathtools>=0.1.1 in /Users/lazywei/.pyenv/versions/2.7.11/lib/python2.7/site-packages (from watchdog>=0.8.3->project-sync)
Installing collected packages: project-sync
Successfully installed project-sync-0.2.0
```

Thanks.

**Comment by corradomatt** [comment]
Thanks for the reply @lazywei -- we're getting closer. Here's my fresh output after clearing pip cache...

```
$ pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)

$ pip install project-sync
Collecting project-sync
  Downloading project_sync-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: Click>=6.0 in /Library/Python/2.7/site-packages (from project-sync)
Collecting watchdog>=0.8.3 (from project-sync)
  Downloading watchdog-0.8.3.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 3.0MB/s
Collecting PyYAML>=3.12 (from project-sync)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 2.8MB/s
Collecting argh>=0.24.1 (from watchdog>=0.8.3->project-sync)
  Downloading argh-0.26.2-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog>=0.8.3->project-sync)
  Downloading pathtools-0.1.2.tar.gz
Installing collected packages: PyYAML, argh, pathtools, watchdog, project-sync
  Found existing installation: PyYAML 3.11
    Uninstalling PyYAML-3.11:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/PyYAML-3.11-py2.7.egg-info/PKG-INFO'
```

Based upon the last line of output I figured it's a path permissions issue, so I ran again as...
``` sudo pip install project-sync```
....and SUCCESS! But this then makes me think I might have permissions issue with how my local pip / python packages are installed. Not really sure though.

Either way, it seems to be working ok and I'll comment here if something is amiss. Thanks again!

**Comment by askulkarni2** [comment]
Works for me now, thanks!

```
$ pip install project-sync                                                                                   
Collecting project-sync
  Downloading project_sync-0.2.0-py2.py3-none-any.whl
Collecting watchdog>=0.8.3 (from project-sync)
  Downloading watchdog-0.8.3.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 3.8MB/s
Requirement already satisfied: Click>=6.0 in /usr/local/home/akulkarni/.pyenv/versions/2.7.11/lib/python2.7/site-packages (from project-sync)
Requirement already satisfied: PyYAML>=3.12 in /usr/local/home/akulkarni/.pyenv/versions/2.7.11/lib/python2.7/site-packages (from project-sync)
Collecting argh>=0.24.1 (from watchdog>=0.8.3->project-sync)
  Downloading argh-0.26.2-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog>=0.8.3->project-sync)
  Downloading pathtools-0.1.2.tar.gz
Installing collected packages: argh, pathtools, watchdog, project-sync
  Running setup.py install for pathtools ... done
  Running setup.py install for watchdog ... done
Successfully installed argh-0.26.2 pathtools-0.1.2 project-sync-0.2.0 watchdog-0.8.3
```

**Comment by lazywei** [comment]
awesome, thanks for following up on this issue @askulkarni2

**Comment by snehiljain34** [comment]
i have cleared out the pip cache, but still the error remains, what should i do now
